theme: minima
title: "AI/ML для школьников 9-11 классов"
description: "22-недельный курс по искусственному интеллекту и машинному обучению для физико-математического лицея"
author: "Ваше имя"
baseurl: ""
url: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - about.md

exclude:
  - README.md
  - LICENSE
